name: shuffle_match
display_name: Shuffle Match
description: A basic game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_fortune_wheel: ^1.3.0
  app_tracking_transparency: ^2.0.6+1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  appsflyer_sdk: ^6.17.5
  shared_preferences: ^2.5.3
  webview_flutter_wkwebview: ^3.23.1
  url_launcher: ^6.3.2
  external_app_launcher: ^4.0.3
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  test: ^1.24.3
  

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

 
flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
  