name: shuffle_match
display_name: Shuffle Match
description: A basic game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  flutter_fortune_wheel: ^1.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  test: ^1.24.3
  

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

 
flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
  